language: php
php:
  - '5.6'
  - '7.1'
  - '7.2'
before_script:
  - phpenv config-rm xdebug.ini
cache:
  directories:
    - vendor
    - src/node_modules
install:
  - cd src && npm install
script:
  - cd src && gulp