<?php

use WP_Mock\Tools\TestCase;

require_once 'vendor/autoload.php';

class WMC_Tests extends TestCase {
	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown() {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}
}