name: WooMinecraft
main: com.plugish.WooMinecraft.WooMinecraft
version: 1.0.3
authors: [JerryWood, TekkitCommando, Phillmac]
description: WooMinecraft Donation Plugin
website:  http://www.tekkitcommando.me

commands:
  woo:
    description: Reload, Register, Check
    usage: |
        /<command> reload - Reload the plugins config.
        /<command> register - register a key.
        /<command> check - check for donations.
permissions:
  woo.admin:
    default: op
    description: Allows the player (or console) to use the woo commands.
